#!/usr/bin/env python3
import argparse
from pathlib import Path


def c_array(name: str, data: bytes) -> str:
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"static const unsigned int {name}_LEN = {len(data)};")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Embed public RDI .text blobs into a C header")
    ap.add_argument("--front", required=True, type=Path, help="front-style RDI .text bin")
    ap.add_argument("--post", required=True, type=Path, help="post-style RDI .text bin")
    ap.add_argument("--front-x86", required=True, type=Path, help="x86 front-style RDI .text bin")
    ap.add_argument("--post-x86", required=True, type=Path, help="x86 post-style RDI .text bin")
    ap.add_argument("-o", "--output", required=True, type=Path)
    args = ap.parse_args()

    front = args.front.read_bytes()
    post = args.post.read_bytes()
    front_x86 = args.front_x86.read_bytes()
    post_x86 = args.post_x86.read_bytes()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "/* Auto-generated by tools/embed_rdi_blobs.py. Do not edit manually. */\n"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        + c_array("RDI_FRONT_V2_OPT", front)
        + "\n\n"
        + c_array("RDI_POST_V2_OPT", post)
        + "\n\n"
        + c_array("RDI_FRONT_X86_OPT", front_x86)
        + "\n\n"
        + c_array("RDI_POST_X86_OPT", post_x86)
        + "\n",
        encoding="ascii",
    )

    print(f"[+] embedded front RDI: {len(front)} bytes")
    print(f"[+] embedded post RDI:  {len(post)} bytes")
    print(f"[+] embedded x86 front RDI: {len(front_x86)} bytes")
    print(f"[+] embedded x86 post RDI:  {len(post_x86)} bytes")
    print(f"[+] output header:      {args.output}")


if __name__ == "__main__":
    main()
